package com.tisov.denis.e2e;

import com.tisov.denis.trader.book.OrderBook;
import com.tisov.denis.trader.domain.OrderIntent;
import com.tisov.denis.trader.domain.OrderType;
import com.tisov.denis.trader.sink.MdEventSink;
import com.tisov.denis.trader.strategy.MarketMakerStrategy;
import com.tisov.denis.trader.strategy.OrderIntentSink;
import com.tisov.denis.trader.walker.ItchMdWalker;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;

@Disabled("Requires data/AMD/01302020.all.itch (~71 MB, generated by ExtractLocateData from the full feed)")
public class PipelineIntegrityTest {

    private static final TickerConfig TICKER = Tickers.AMD;
    private static final OrderBookConfig OB = TICKER.orderBookConfig();
    private static final StrategyConfig ST = TICKER.strategyConfig();

    private static final Path FILE = Path.of("../data/%s/01302020.all.itch".formatted(TICKER.ticker()));

    @Test
    void replayHoldsPipelineInvariants() throws IOException {
        InvariantSink intents = new InvariantSink();
        Pipeline pipeline = Replay.build(TICKER, intents);
        OrderBook book = pipeline.book();

        long[] events = {0};
        int[] bookCrossings = {0};
        int[] poolOverflow = {0};
        MdEventSink checker = e -> {
            if (e.locate() != TICKER.locate()) {
                return;
            }
            pipeline.sink().onEvent(e);
            events[0]++;
            long bid = book.bestBid();
            long ask = book.bestAsk();
            if (bid != OrderBook.NO_QUOTE && ask != OrderBook.NO_QUOTE && bid >= ask) {
                bookCrossings[0]++;
            }
            if (book.liveOrders() > OB.poolCapacity()) {
                poolOverflow[0]++;
            }
        };

        new ItchMdWalker(checker).walk(Replay.map(FILE));

        System.out.printf("integrity: events=%,d  intents=%,d  bookCrossings=%d  badIntents=%d  poolOverflow=%d%n",
                events[0], intents.count, bookCrossings[0], intents.bad, poolOverflow[0]);
        assertThat(events[0]).as("%s events processed".formatted(TICKER.ticker())).isEqualTo(2_367_456L);
        assertThat(intents.count).as("strategy quoted").isEqualTo(336472L);
        assertThat(bookCrossings[0]).as("book never locks/crosses").isZero();
        assertThat(intents.bad).as("every quote is LIMIT/QTY/positive").isZero();
        assertThat(poolOverflow[0]).as("no pool-slot leak").isZero();
    }

    private static final class InvariantSink implements OrderIntentSink {
        long count;
        int bad;

        @Override
        public void onIntent(OrderIntent i) {
            count++;
            if (i.orderType() != OrderType.LIMIT || i.quantity() != ST.qty() || i.price() <= 0) {
                bad++;
            }
        }
    }
}
